force-app/main/default/objects/Tracking__c/Tracking__c.object-meta.xml
<CustomObject>
    <label>Tracking</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>N° Tracking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trackings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Tracking__c/fields/Functionality__c.field-meta.xml
<CustomField>
    <fullName>Functionality__c</fullName>
    <label>Fynctionality</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/controllers/TrackingServiceControllerTest.cls
@IsTest
private class TrackingServiceControllerTest{

	@IsTest
	static void commitTrackingShouldReturnSuccess(){
		fflib_ApexMocks mocks = new fflib_ApexMocks();
		fflib_ISObjectUnitOfWork uowMock = new fflib_SObjectMocks.SObjectUnitOfWork(mocks);

		String functionality = 'test';

		Application.UnitOfWork.setMock(uowMock);

		Test.startTest();
		Map<String, Object> result = TrackingServiceController.commitTracking(functionality);
		Test.stopTest();

		((fflib_ISObjectUnitOfWork)mocks.verify(uowMock)).registerNew(
			fflib_Match.sObjectWith(new Map<SObjectField, Object>{
				Schema.Tracking__c.Functionality__c => functionality}));
		((fflib_ISObjectUnitOfWork)mocks.verify(uowMock)).commitWork();

		Assert.success(result);
	}

	@IsTest
	static void commitTrackingShouldReturnErrorAndCommitOneLog(){
		Test.startTest();
		Map<String, Object> result = TrackingServiceController.commitTracking(null);
		Test.stopTest();

		Assert.errorWithLog(result);
	}
}