force-app/main/default/objects/Tracking__c/Tracking__c.object-meta.xml
<CustomObject>
    <label>Tracking</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>N° Tracking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trackings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Tracking__c/fields/Functionality__c.field-meta.xml
<CustomField>
    <fullName>Functionality__c</fullName>
    <label>Fynctionality</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/controllers/TrackingServiceController.cls
public without sharing class TrackingServiceController{

	@AuraEnabled
	public static Map<String, Object> commitTracking(String functionality){
		Map<String, Object> result = new Map<String, Object>();
		try{
			fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance(new List<SObjectType>{ Tracking__c.SObjectType });
			uow.registerNew(new Tracking__c(Functionality__c = functionality));
			uow.commitWork();
			result.put(Constants.STATUS, Constants.SUCCESS);
		}catch(Exception e){
			LogFactory.commitError(TrackingServiceController.class, 'commitTracking', new List<Object>{ functionality }, e);
			result.put(Constants.STATUS, Constants.ERROR);
			result.put(Constants.MESSAGE, e.getMessage());
		}
		return result;
	}
}