force-app/main/default/objects/ContentVersion/fields/FileType__c.field-meta.xml
<CustomField>
    <fullName>FileType__c</fullName>
    <label>File type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FileTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/FileTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Test</fullName>
    </customValue>
    <masterLabel>File types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/domains/contentVersions/triggerHandlers/ContentVersionDefaultValueTest.cls
@IsTest
private class ContentVersionDefaultValueTest{

	@TestSetup
	static void setup(){
		UserBuilder.newStandardUser().build();
	}

	@IsTest
	static void createFileWithJSONShouldHaveFieldsValueFilled(){
		User standardUser = TestUtils.selectStandardUser();
		System.runAs(standardUser){
			String json = '{"tlz__FileType__c":"Test"}';

			Test.startTest();
			ContentVersion cv = ContentVersionBuilder.newFile('Mandat').withJSON(json).build();
			Test.stopTest();

			ContentVersion cvAfter = [SELECT FileType__c FROM ContentVersion WHERE Id = :cv.Id];
			Assert.equals('Test', cvAfter.FileType__c);
		}
	}
}