force-app/main/default/objects/ContentVersion/fields/JSON_fileupload__c.field-meta.xml
<CustomField>
    <fullName>JSON_fileupload__c</fullName>
    <description>If you want to change the file type when you upload a file, you can for instance fill this field with the JSON { Type__c: &quot;example&quot; }, then a trigger will parse the JSON to fill the ContentVersion fields</description>
    <label>JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/PrivateFile__c.field-meta.xml
<CustomField>
    <fullName>PrivateFile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Private file</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/builders/ContentVersionBuilder.cls
@IsTest
public inherited sharing class ContentVersionBuilder extends SObjectBuilder{

	private ContentVersionBuilder(){
		super();
	}

	private SObjectType getSObjectType(){
		return ContentVersion.SObjectType;
	}

	public ContentVersion build(){
		ContentVersion contentVersion = (ContentVersion)buildRecord();
		return [SELECT Id, Type__c, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id];
	}

	public static ContentVersionBuilder newFile(String title){
		return new ContentVersionBuilder()
			.withTitle(title)
			.withPathOnClient(title)
			.withVersionData(Blob.valueOf('Test'));
	}

	public static ContentVersionBuilder newFile(){
		return newFile('TestFile');
	}

	public ContentVersionBuilder withTitle(String title){
		setFieldValue(ContentVersion.Title, title);
		return this;
	}

	public ContentVersionBuilder withPathOnClient(String pathOnClient){
		setFieldValue(ContentVersion.PathOnClient, pathOnClient);
		return this;
	}

	public ContentVersionBuilder withRecord(SObject record){
		setFieldValue(ContentVersion.RecordId__c, record.Id);
		return this;
	}

	public ContentVersionBuilder withVersionData(Blob versionData){
		setFieldValue(ContentVersion.VersionData, versionData);
		return this;
	}

	public ContentVersionBuilder withJSON(String json){
		setFieldValue(ContentVersion.JSON_fileupload__c, json);
		return this;
	}

	public ContentVersionBuilder withPrivateFile(Boolean privateFile){
		setFieldValue(ContentVersion.PrivateFile__c, privateFile);
		return this;
	}
}