force-app/main/default/objects/ContentVersion/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/RelatedToRecord__c.field-meta.xml
<CustomField>
    <fullName>RelatedToRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Related to record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/domains/contentDocumentLinks/triggerHandlers/ContentDocumentLinkRecordTest.cls
@IsTest
private class ContentDocumentLinkRecordTest{

	@TestSetup
	static void setup(){
		User standardUser = UserBuilder.newStandardUser().build();
		System.runAs(standardUser){
			AccountBuilder.newAccount().build();
		}
	}

	@IsTest
	static void linkFileOnAccountShouldFillRecordIdOnContentVersionWithAccountnId(){
		User standardUser = TestUtils.selectStandardUser();
		System.runAs(standardUser){
			Account account = TestUtils.selectAccount();
			ContentVersion cv = ContentVersionBuilder.newFile().build();

			Test.startTest();
			ContentDocumentLinkBuilder.newContentDocumentLink(cv, account).build();
			Test.stopTest();

			ContentVersion contentVersionAfter = [SELECT RecordId__c, RelatedToRecord__c FROM ContentVersion WHERE Id = :cv.Id];
			Assert.equals(account.Id, contentVersionAfter.RecordId__c);
			Assert.isTrue(contentVersionAfter.RelatedToRecord__c);
		}
	}
}