force-app/main/default/objects/ContentVersion/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/RelatedToRecord__c.field-meta.xml
<CustomField>
    <fullName>RelatedToRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Related to record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/domains/contentVersions/triggerHandlers/ContentVersionRecordRelation.cls
public with sharing class ContentVersionRecordRelation extends ContentVersionsHandler{

	private ContentVersionRecordRelation(ContentVersions domain, fflib_ISObjectUnitOfWork uow){
		super(domain, uow);
	}

	public static ContentVersionRecordRelation handleInsert(ContentVersions domain, fflib_ISObjectUnitOfWork uow){
		return new ContentVersionRecordRelation(domain, uow);
	}

	public void handleRecordIdIfFilled(){
		for(ContentVersion contentVersion : contentVersions){
			if(String.isNotBlank(contentVersion.RecordId__c) && !contentVersion.RelatedToRecord__c){
				uow.registerNew(new ContentDocumentLink(
					ContentDocumentId = contentVersion.ContentDocumentId,
					LinkedEntityId = contentVersion.RecordId__c
				));
				uow.registerDirty(new ContentVersion(
					Id = contentVersion.Id,
					RelatedToRecord__c = true
				), new List<SObjectField>{
					Schema.ContentVersion.RelatedToRecord__c
				});
			}
		}
	}
}