force-app/main/default/objects/SObjectHistory__c/SObjectHistory__c.object-meta.xml
<CustomObject>
    <label>SObject History</label>
    <nameField>
        <displayFormat>H-{00000000}</displayFormat>
        <label>History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SObject Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SObjectHistory__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/controllers/RecordHistoryControllerTest.cls
@IsTest
private class RecordHistoryControllerTest{

	@IsTest
	static void getHistoryShouldReturnOneRecord(){
		User standardUser = UserBuilder.newStandardUser().build();
		System.runAs(standardUser){
			Account account = AccountBuilder.newAccount().build();
			SObjectHistory__c history = new SObjectHistory__c(RecordId__c = account.Id);
			insert history;

			Test.startTest();
			List<SObjectHistory__c> records = RecordHistoryController.getHistory(account.Id);
			Test.stopTest();

			Assert.equals(1, records.size());
		}
	}
}