force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex class</fullName>
            </value>
            <value>
                <fullName>Lightning component</fullName>
            </value>
            <value>
                <fullName>Webservice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/builders/SObjectBuilderTest.cls
@IsTest
global class SObjectBuilderTest{

	@IsTest
	static void logBuilderShouldCreateRecord(){
		SObjectBuilder builder = new LogBuilder(LogConstants.RT_ERROR)
			.setFieldValue(Log__c.Type__c, LogConstants.TYPE_APEX)
			.setFieldValue('Message__c', 'message');

		Log__c recordWithoutId = (Log__c)builder.buildRecordWithoutCommit();
		Assert.isNull(recordWithoutId.Id);

		Log__c recordWithId = (Log__c)builder.buildRecord();
		Assert.isNotNull(recordWithId.Id);

		List<Log__c> logsCreated = (List<Log__c>)LogBuilder.build(new List<SObjectBuilder>{ builder });
		Assert.equals(1, logsCreated.size());
		Assert.isNotNull(logsCreated[0].Id);

		Map<String, SObject> logsCreatedMap = (Map<String, SObject>)LogBuilder.buildRecords(new Map<String, SObjectBuilder>{ 'log' => builder });
		Assert.equals(1, logsCreatedMap.size());
		Assert.isNotNull(logsCreatedMap.get('log')?.Id);
	}

	global class LogBuilder extends SObjectBuilder{

		global LogBuilder(){
			super();
		}

		global LogBuilder(String recordTypeDeveloperName){
			super(recordTypeDeveloperName);
		}

		global override SObjectType getSObjectType(){
			return Log__c.SObjectType;
		}
	}
}