force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex class</fullName>
            </value>
            <value>
                <fullName>Lightning component</fullName>
            </value>
            <value>
                <fullName>Webservice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/models/DecoratedPicklistEntryTest.cls
@IsTest
private class DecoratedPicklistEntryTest{

	@IsTest
	static void testsForInstanciationAndMethods(){
		DecoratedPicklistEntry picklistEntry = DecoratedPicklistEntry.newInstance('label');
		Assert.equals('label', picklistEntry.value);
		Assert.equals('label', picklistEntry.label);

		picklistEntry = DecoratedPicklistEntry.newInstance('value', 'label');
		Assert.equals('value', picklistEntry.value);
		Assert.equals('label', picklistEntry.label);

		List<RecordTypeInfo> recordTypes = SObjectUtils.getRecordTypes(Log__c.SObjectType);
		picklistEntry = DecoratedPicklistEntry.newInstance(recordTypes[0]);
		Assert.equals(recordTypes[0].getRecordTypeId(), picklistEntry.value);
		Assert.equals(recordTypes[0].getName(), picklistEntry.label);
		Assert.equals(recordTypes[0].getDeveloperName(), picklistEntry.fields?.get('developerName'));

		Account account = new Account(
			Id = fflib_IDGenerator.generate(Schema.Account.SObjectType),
			Name = 'toto'
		);
		picklistEntry = DecoratedPicklistEntry.newInstanceFromSObject(account);
		Assert.equals(account.Id, picklistEntry.value);
		Assert.equals(account.Name, picklistEntry.label);

		Contact contact = (Contact)TestUtils.setReadableFields(new Contact(
			Id = fflib_IDGenerator.generate(Schema.Contact.SObjectType),
			Salutation = 'Mr.'
		), new Map<String, Object>{
			'Name' => 'Tutu'
		});
		picklistEntry = DecoratedPicklistEntry.newInstanceFromSObject(contact);
		Assert.equals(contact.Id, picklistEntry.value);
		Assert.equals('Mr. Tutu', picklistEntry.label);

		List<DecoratedPicklistEntry> picklistEntries = new List<DecoratedPicklistEntry>();
		for(Schema.PicklistEntry entry : Log__c.Type__c.getDescribe(FieldDescribeOptions.DEFAULT).getPicklistValues())
			picklistEntries.add(DecoratedPicklistEntry.newInstanceFromPicklistEntry(entry));
		Assert.isFalse(picklistEntries.isEmpty());

		Log__c log = new Log__c(
			Type__c = LogConstants.TYPE_APEX,
			Message__c = 'message'
		);
		picklistEntry = DecoratedPicklistEntry.newInstanceFromPicklist(log, Log__c.Type__c)
			.setFieldValue(log, new List<SObjectField>{ Log__c.Message__c })
			.addDescription(new List<String>{'toto', 'tutu'});
		Assert.equals(LogConstants.TYPE_APEX, picklistEntry.value);
		Assert.equals(LogConstants.TYPE_APEX, picklistEntry.label);
		Assert.equals('message', picklistEntry.fields.get('tlz__Message__c'));
		Assert.equals('toto • tutu', picklistEntry.description);

		picklistEntry = DecoratedPicklistEntry.newNoneOption();
		Assert.equals(Constants.EMPTY, picklistEntry.value);
		Assert.equals(Constants.NONE, picklistEntry.label);
	}
}